services:
  log-output:
    image: palolaur/pingpong
    build:
      context: .
      tags:
        - palolaur/pingpong:${APP_VERSION}
        - palolaur/pingpong:latest
    ports:
      - "8000:8000"
